name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-arch:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pacman -Syu --noconfirm base-devel rust

      - name: Build Arch package
        run: makepkg -sf --noconfirm

      - name: Upload Arch package
        uses: actions/upload-artifact@v2
        with:
          name: pokerust.pkg.tar.zst
          path: ./*.pkg.tar.zst

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y dpkg-dev

      - name: Build Debian package
        run: ./build/debian.sh

      - name: Upload Debian package
        uses: actions/upload-artifact@v2
        with:
          name: pokerust.deb
          path: ./build/debian/pokerust.deb
